In [1]:
import numpy as np
import random
import matplotlib.pyplot as plt
from func import neuron_layer,neuron_layers

In [2]:
my_layers = neuron_layers([1,2,3,2],0.0000005)

The Mosttt  3


In [3]:
data = np.reshape(np.array([2]) , (1,1))
expected = np.reshape(np.array([2]), (1,1))

err , out = my_layers.calc_output(data,expected)


 
 |||| In neuron 0
Forward Calculations || W.x + b || == a 

W -> 
 [[1.]
 [1.]], x -> 
 [[2]], b -> 
 [[0.97405567]
 [0.80565397]]
----
a -> [[2.97405567]
 [2.80565397]]
Nonlinear ||σ(a) = y|| == a 

a -> [[2.97405567]
 [2.80565397]] 
σ(a) -> [[0.95138819]
 [0.94298059]]
-------------------------


 
 |||| In neuron 1
Forward Calculations || W.x + b || == a 

W -> 
 [[1. 1.]
 [1. 1.]
 [1. 1.]], x -> 
 [[0.95138819]
 [0.94298059]], b -> 
 [[0.42948737]
 [0.25157042]
 [0.68798628]]
----
a -> [[2.32385615]
 [2.1459392 ]
 [2.58235506]]
Nonlinear ||σ(a) = y|| == a 

a -> [[2.32385615]
 [2.1459392 ]
 [2.58235506]] 
σ(a) -> [[0.91083362]
 [0.8952887 ]
 [0.92971731]]
-------------------------

Forward Calculations || W.x + b || == a 

W -> 
 [[1. 1. 1.]
 [1. 1. 1.]], x -> 
 [[0.91083362]
 [0.8952887 ]
 [0.92971731]], b -> 
 [[0.17721056]
 [0.46902924]]
----
a -> [[2.91305019]
 [3.20486887]]
-------------------------


 
 |||| In neuron 2
Forward Calculations || W.x + b || == a 

W -> 
 [[1.

In [4]:
for i in my_layers.layers:
    print("X values \n{}, W values \n{}, Sig values\n{}".format(i.x,i.w,i.sig))

#print("\n\n",(out-expected)**2)
#print(err) ## Mean squarer error

print("\n Error\n {}".format(my_layers.layers[-1].j))

X values 
[[2]], W values 
[[1.]
 [1.]], Sig values
[[0.95138819]
 [0.94298059]]
X values 
[[0.95138819]
 [0.94298059]], W values 
[[1. 1.]
 [1. 1.]
 [1. 1.]], Sig values
[[0.91083362]
 [0.8952887 ]
 [0.92971731]]
X values 
[[0.91083362]
 [0.8952887 ]
 [0.92971731]], W values 
[[1. 1. 1.]
 [1. 1. 1.]], Sig values
[[0.]
 [0.]]

 Error
 [[0.83366066]
 [1.451709  ]]


In [5]:
my_layers.layers[1].x

array([[0.95138819],
       [0.94298059]])

In [8]:
da_dw = -2*err

##### 1- w_1*x  + b_1 = a_0      || Layer 1
##### 2- c_0 = σ(a_0)
##### 3- w_2*c_0 + b_2 = a_1     || Layer 2
##### 4- c_1 = σ(a_1) 
##### 5- w_3*c_1 + b_3 = a_2     || Layer 3 (Output Layer)

##### First weigtth derivatives
#####
##### dJ/dw_2 = [ (dJ/dy)*(dy/da) ] * d_c1
##### --> Send for other derivatives dJ/dc = [ (dJ/dy)*(dy/da) ]*w

######## dC/dw_2 = (dC/dy)*(dy/da_2)*(da_2/d_c1)*(dc_1/d_a1)*(da_1/dw_2)
##### (dJ/dy)   = -2J
##### (dy/da_2) = 1
##### (da_2/d_c1) = w_3
##### (dc_1/d_a1) = -c_1(1-c_1)
##### (da_1/dw_2) = c_0

##### dw_2 @ layer[1]

dJ_da = -2*my_layers.layers[-1].j 
a = (len(my_layers.layers) - 1 )

for i in range(0,3):

    print("!!! Neuron ",a)
    print(np.shape(dJ_da),np.shape(my_layers.layers[a].x),type(my_layers.layers[a].x))

    if a == (len(my_layers.layers) - 1 ):
        dJ_da = dJ_da.T
        # No activation layer
    else:
        dJ_da = dJ_da * my_layers.layers[a].sig.T
        
    print(type(my_layers.layers[a].x),np.shape(my_layers.layers[a].x))

    dJ_dw = dJ_da.T @  my_layers.layers[a].x.T
    
    da_dc = my_layers.layers[a].w
    
    dJ_dc = dJ_da @ da_dc

    dJ_da = dJ_dc ## Pass down


    print("Derivatives of the weigth factos \n {} \n".format(dJ_dw))
    print(np.shape(dJ_dw))

    a = a-1






!!! Neuron  2
(2, 1) (3, 1) <class 'numpy.ndarray'>
<class 'numpy.ndarray'> (3, 1)
Finally (2, 3)
!!! Neuron  1
(1, 3) (2, 1) <class 'numpy.ndarray'>
Sigmoid shape (3, 1), Passed down shape (1, 3)
(1, 3)
<class 'numpy.ndarray'> (2, 1)
Finally (3, 2)
!!! Neuron  0
(1, 2) (1, 1) <class 'numpy.ndarray'>
Sigmoid shape (2, 1), Passed down shape (1, 2)
(1, 2)
<class 'numpy.ndarray'> (1, 1)
Finally (2, 1)


In [7]:
my_layers.back_prop()

ValueError: operands could not be broadcast together with shapes (2,1) (3,1) 